import { League_Spartan } from "next/font/google";
import "./globals.css";
import ReactLenis from 'lenis/react'

const font = League_Spartan({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${font.className} antialiased`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
